---
language: ruby
sudo: false
cache: bundler
language: ruby
bundler_args: --without metrics
script: "bundle exec rake ci"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.5
  - 2.3.1
  - ruby-head
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
    - rvm: rbx-2
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
branches:
  only: master
notifications:
  email: false
